### ISSUE TITLE
erros installing provisions

### ISSUE THREAD

**Issue by karneaud** [drmyersii/vagrant-env-basher#30]
I tried to install your project using the latest repo and ran into this error

> ==> default: Traceback (most recent call last):
> ==> default:   File "/usr/bin/add-apt-repository", line 91, in <module>
> ==> default:     sp = SoftwareProperties(options=options)
> ==> default:   File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 119, in **init**
> ==> default:     self.apt_key = AptAuth(rootdir=rootdir)
> ==> default:   File "/usr/lib/python3/dist-packages/softwareproperties/AptAuth.py", line 52, in **init**
> ==> default:     self.tmpdir = tempfile.mkdtemp()
> ==> default:   File "/usr/lib/python3.4/tempfile.py", line 426, in mkdtemp
> ==> default:     dir = gettempdir()
> ==> default:   File "/usr/lib/python3.4/tempfile.py", line 370, in gettempdir
> ==> default:     tempdir = _get_default_tempdir()
> ==> default:   File "/usr/lib/python3.4/tempfile.py", line 312, in _get_default_tempdir
> ==> default:     dirlist)
> ==> default: FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/home/vagrant']
> ==> default: Error in sys.excepthook:
> ==> default: Traceback (most recent call last):
> ==> default:   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
> ==> default:     os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
> ==> default: OSError: [Errno 30] Read-only file system: '/var/crash/_usr_bin_add-apt-repository.0.crash'
> ==> default: 
> ==> default: Original exception was:
> ==> default: Traceback (most recent call last):
> ==> default:   File "/usr/bin/add-apt-repository", line 91, in <module>
> ==> default:     sp = SoftwareProperties(options=options)
> ==> default:   File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 119, in __init__
> ==> default:     self.apt_key = AptAuth(rootdir=rootdir)
> ==> default:   File "/usr/lib/python3/dist-packages/softwareproperties/AptAuth.py", line 52, in **init**
> ==> default:     self.tmpdir = tempfile.mkdtemp()
> ==> default:   File "/usr/lib/python3.4/tempfile.py", line 426, in mkdtemp
> ==> default:     dir = gettempdir()
> ==> default:   File "/usr/lib/python3.4/tempfile.py", line 370, in gettempdir
> ==> default:     tempdir = _get_default_tempdir()
> ==> default:   File "/usr/lib/python3.4/tempfile.py", line 312, in _get_default_tempdir
> ==> default:     dirlist)
> ==> default: FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/home/vagrant']

Not sure what it means to be honest.....

**Comment by davidmyersdev** [comment]
Closing to consolidate issues. This is likely another side effect of #29. Feel free to re-open if this is not the case.
