### ISSUE TITLE
Error instilling node

### ISSUE THREAD

**Issue by karneaud** [drmyersii/vagrant-env-basher#31]
Been at this for hours but to no avail

Trying to run `vagrant provision` to install node and nam using your latest repo on Yosemite but keep getting

> ==> default: Now using node v6.3.1 (npm v3.10.3)
> ==> default: Creating default alias: default -> node (-> v6.3.1)
> ==> default: default -> node (-> v6.3.1)
> ==> default: Now using node v6.3.1 (npm v3.10.3)
> ==> default: npm
> ==> default:  
> ==> default: WARN
> ==> default:  
> ==> default: optional
> ==> default:  Skipping failed optional dependency /pm2/chokidar/fsevents:
> ==> default: npm
> ==> default:  
> ==> default: WARN
> ==> default:  
> ==> default: notsup
> ==> default:  Not compatible with your operating system or architecture: fsevents@1.0.14
> ==> default: npm
> ==> default:  
> ==> default: ERR!
> ==> default:  Linux 3.13.0-93-generic
> ==> default: npm
> ==> default:  
> ==> default: ERR!
> ==> default:  
> ==> default: argv
> ==> default:  "/home/vagrant/.nvm/versions/node/v6.3.1/bin/node" "/home/vagrant/.nvm/versions/node/v6.3.1/bin/npm" "install" "-g" "npm" "pm2"
> ==> default: npm
> ==> default:  
> ==> default: ERR!
> ==> default:  
> ==> default: node
> ==> default:  v6.3.1
> ==> default: npm
> ==> default:  
> ==> default: ERR!
> ==> default:  
> ==> default: npm 
> ==> default:  v3.10.3
> ==> default: npm
> ==> default:  
> ==> default: ERR!
> ==> default:  
> ==> default: file
> ==> default:  /home/vagrant/.npm/kind-of/3.0.4/package/package.json
> ==> default: npm
> ==> default:  
> ==> default: ERR!
> ==> default:  code EJSONPARSE
> ==> default: 
> ==> default: npm ERR! Failed to parse json
> ==> default: npm ERR!
> ==> default:  No data, empty input at 1:1
> ==> default: npm
> ==> default:  
> ==> default: ERR!
> ==> default:  
> ==> default: npm
> ==> default:  
> ==> default: ERR!
> ==> default:  ^
> ==> default: npm
> ==> default:  
> ==> default: ERR!
> ==> default:  File: /home/vagrant/.npm/kind-of/3.0.4/package/package.json
> ==> default: npm
> ==> default:  
> ==> default: ERR!
> ==> default:  Failed to parse package.json data.
> ==> default: npm
> ==> default:  
> ==> default: ERR!
> ==> default:  package.json must be actual JSON, not just JavaScript.
> ==> default: npm
> ==> default:  
> ==> default: ERR!
> ==> default:  
> ==> default: npm
> ==> default:  
> ==> default: ERR!
> ==> default:  This is not a bug in npm.
> ==> default: npm
> ==> default:  
> ==> default: ERR!
> ==> default:  Tell the package author to fix their package.json file. JSON.parse
> ==> default: npm
> ==> default:  
> ==> default: ERR!
> ==> default:  Please include the following file with any support request:
> ==> default: npm
> ==> default:  
> ==> default: ERR!
> ==> default:      /home/vagrant/npm-debug.log
> The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.

not sure what it means at the moment.

**Comment by davidmyersdev** [comment]
It sounds to me like your `package.json` (or at least the one in that package) has an error or a typo. I believe this is not an issue with Vagrant or this project.

**Comment by karneaud** [comment]
I'm not even sure anymore.... I had successfully used an older version of your box and it worked with just node but didn't with php....I upgraded and now it works with php/ composer but not with node/ npm.... I gave up trying.

**Comment by davidmyersdev** [comment]
I'm guessing the reason it wasn't working with node was due to you having your `args_npm_install_dir` set to `/vagrant` instead of `/home/vagrant/app` as you had set for the other configurations. I replied in #29 with a new Vagrantfile that I hope works for you to solve all of these issues.

**Comment by davidmyersdev** [comment]
Closing to consolidate issues. This is likely another side effect of #29. Feel free to re-open if this is not the case.
